---
name: Approve pull requests
run-name: Approve pull requests (${{github.event.issue.number}})
on: issue_comment
jobs:
  approve:
    name: Approve a pull request (${{github.event.issue.number}})
    runs-on: ubuntu-24.04
    if: github.event.issue.pull_request && github.event.comment.body == '/approve'
    timeout-minutes: 10
    permissions:
      pull-requests: read
      contents: read
    steps:
      - uses: csm-actions/approve-pr-action@452271472f121d6d2f8e7a0761488d2fcc29b715 # v0.2.0
        with:
          pull_request_number: ${{ github.event.issue.number }}
          app_id: ${{vars.TEST_CLIENT_APP_ID}}
          app_private_key: ${{secrets.TEST_CLIENT_PRIVATE_KEY}}
          server_repository_name: test-server
