---
name: Update pull request branch by pull request comment
on: issue_comment
jobs:
  update_branch:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions: {}
    if: github.event.issue.pull_request && contains(fromJSON('["/update-branch", "/ub"]'), github.event.comment.body)
    steps:
      - uses: csm-actions/update-branch-action@82d7f19f08ac511384ab0f3f867e3592ba140c07 # v0.1.2
        with:
          app_id: ${{vars.TEST_CLIENT_APP_ID}}
          app_private_key: ${{secrets.TEST_CLIENT_PRIVATE_KEY}}
          server_repository_name: test-server
